=== Sun42/zia/another_zia_rev/includes/zia_api/conf/plugin_conf.dtd
<!--
	ZIA API - epitech_2011s
	Copyright Â© EPITECH 2009

	Plugin XML configuration file DTD.

	For check XML file with this DTD, try something like that:
		xmllint - -valid - -noout plugin_conf.xml

	or if the DTD path is not directly accessible:
		xmllint - -valid - -noout - -dtdvalid plugin_conf.dtd plugin_conf.xml

	Note: remove space between '-' (yes, XML DTD specification sucks).
-->

<!ELEMENT hives ( hive* )>

<!ELEMENT hive ( entry+ )>
<!ATTLIST hive name CDATA #REQUIRED>

<!ELEMENT entry ( #PCDATA )>
<!ATTLIST entry key CDATA #REQUIRED>

=== Sun42/zia/another_zia_rev/doc/xmlConf/libZiaCore.xml
<?xml version="1.0" encoding="UTF-8"  standalone="no"?>
<!DOCTYPE plugin_conf SYSTEM "plugin_conf.dtd">

<hives>
  <hive name="GenericType">
  <entry key="html">text/html</entry>
  <entry key="txt">text/plain</entry>
  <entry key="mp3">audio/mpeg</entry>
  <entry key="avi">video/x-msvideo</entry>
  <entry key="mpeg">video/mpeg</entry>
  <entry key="mpeg">video/mpeg</entry>
  <entry key="mpeg">video/mpg</entry>
  <entry key="flv">video/x-flv</entry>
  <entry key="ogv">video/ogg</entry>
  <entry key="mp4">video/mp4</entry>
  <entry key="mp3">audio/mpeg</entry>
  <entry key="pl">text/x-perl</entry>
  <entry key="pm">text/x-perl</entry>
  <entry key="py">text/x-python</entry>
  <entry key="ico">image/x-icon</entry>
  <entry key="png">image/png</entry>
  <entry key="jpeg">image/jpeg</entry>
  <entry key="jpg">image/jpeg</entry>
  <entry key="jpe">image/jpeg</entry>
  <entry key="gif">image/gif</entry>
  <entry key="xml">application/xml</entry>
  <entry key="xsl">application/xml</entry>
  <entry key="xsd">application/xml</entry>
  <entry key="xhtml">application/xhtml+xm</entry>
  <entry key="rss">application/rss+xml</entry>
  <entry key="js">application/javascript</entry>
  <entry key="ogg">audio/ogg</entry>
  <entry key="gtar">application/x-gt</entry>ar
  <entry key="tgz">application/x-gtar</entry>
  <entry key="rb">application/x-ruby</entry>
  <entry key="php4">application/x-httpd-php4</entry>
  <entry key="php">application/x-httpd-php</entry>
  <entry key="es">application/ecmascript</entry>
  </hive>
</hives>

=== Sun42/zia/ZiaProject/build/ZiaConf.xml
<?xml version="1.0" encoding="UTF-8"  standalone="no"?>
<!DOCTYPE plugin_conf SYSTEM "plugin_conf.dtd">

<!--
    Exemple de conf pour notre serveur
    mettre le fichier de confi a cote du binaire du zia et le nomme ZiaConf.xml
-->

<hives>
  <hive name="Ports">
    <entry key="SSL">43000</entry>
    <entry key="Http">80</entry>
    <entry key="PluginLoader">42000</entry>
  </hive>
  <hive name="Main">
    <entry key="RootDirectory">/var/www</entry>
    <entry key="ServerAdmin">youa@your.address</entry>
    <entry key="ServerName">Zia</entry>
    <entry key="LogsDirectory">../logs/</entry>
    <entry key="KeepAlive">On</entry>
    <entry key="MaxKeepAlive">300</entry>
  </hive>
  <hive name="Plugins">
    <entry key="LoadPlugin">
      
    </entry>
    <entry key="LoadDirectory">
      ../libs/
    </entry>
  </hive>
</hives>
